/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  googlecalendar: import("./googlecalendar/api"),
  googlevideo: import("./googlevideo/api"),
  "mock-payment-app": import("./mock-payment-app/api"),
  paypal: import("./paypal/api"),
  "routing-forms": import("./routing-forms/api"),
  salesforce: import("./salesforce/api"),
  stripepayment: import("./stripepayment/api"),
  vital: import("./vital/api"),
  zoomvideo: import("./zoomvideo/api"),
};
