/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { metadata as dailyvideo__metadata_ts } from "./dailyvideo/_metadata";
import { metadata as googlecalendar__metadata_ts } from "./googlecalendar/_metadata";
import { metadata as googlevideo__metadata_ts } from "./googlevideo/_metadata";
import mock_payment_app_config_json from "./mock-payment-app/config.json";
import paypal_config_json from "./paypal/config.json";
import routing_forms_config_json from "./routing-forms/config.json";
import salesforce_config_json from "./salesforce/config.json";
import { metadata as stripepayment__metadata_ts } from "./stripepayment/_metadata";
import { metadata as vital__metadata_ts } from "./vital/_metadata";
import { metadata as zoomvideo__metadata_ts } from "./zoomvideo/_metadata";

export const appStoreMetadata = {
  dailyvideo: dailyvideo__metadata_ts,
  googlecalendar: googlecalendar__metadata_ts,
  googlevideo: googlevideo__metadata_ts,
  "mock-payment-app": mock_payment_app_config_json,
  paypal: paypal_config_json,
  "routing-forms": routing_forms_config_json,
  salesforce: salesforce_config_json,
  stripepayment: stripepayment__metadata_ts,
  vital: vital__metadata_ts,
  zoomvideo: zoomvideo__metadata_ts,
};
