/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { metadata as dailyvideo__metadata_ts } from "./dailyvideo/_metadata";
import { metadata as googlevideo__metadata_ts } from "./googlevideo/_metadata";
import { metadata as zoomvideo__metadata_ts } from "./zoomvideo/_metadata";

export const appStoreMetadata = {
  dailyvideo: dailyvideo__metadata_ts,
  googlevideo: googlevideo__metadata_ts,
  zoomvideo: zoomvideo__metadata_ts,
};
